jarvis-mcmc_api:
  restart: always
  build: ./jarvis-mcmc_api
  expose:
    - "8080"
  ports:
    - "8080:8080"
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 4 --bind :8080 main:app

proxy:
  restart: always
  build: ./proxy
  expose:
    - "80"
  ports:
    - "80:80"
  volumes_from:
    - jarvis-mcmc_api
  links:
    - jarvis-mcmc_api:jarvis-mcmc_api
